# Generated by Django 3.0.3 on 2020-08-31 19:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('cuisine', models.CharField(max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Prep_methods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(max_length=30)),
                ('types', models.TextField()),
                ('about', models.URLField(default='https://en.wikipedia.org/wiki/Outline_of_food_preparation#Food_preparation_techniques')),
            ],
        ),
        migrations.CreateModel(
            name='ItemProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('veg', models.BooleanField()),
                ('ingredients', models.TextField()),
                ('recipe', models.TextField()),
                ('num_tasks', models.PositiveIntegerField(blank=True, null=True)),
                ('stations', models.TextField(default='List of stations for the item.')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assembly.Item')),
            ],
        ),
    ]
